// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActiveUserBadge: typeof import('./components/ActiveUserBadge.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Carbon3dMprToggle: typeof import('~icons/carbon/3d-mpr-toggle')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonChat: typeof import('~icons/carbon/chat')['default']
    CarbonCheckmarkFilled: typeof import('~icons/carbon/checkmark-filled')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    SignIn: typeof import('./components/SignIn.vue')['default']
  }
}

export { }
