// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActiveUserBadge: typeof import('./components/ActiveUserBadge.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Carbon3dMprToggle: typeof import('~icons/carbon/3d-mpr-toggle')['default']
    CarbonChat: typeof import('~icons/carbon/chat')['default']
    CarbonContourFinding: typeof import('~icons/carbon/contour-finding')['default']
    CarbonFaceDissatisfied: typeof import('~icons/carbon/face-dissatisfied')['default']
    CarbonFaceDissatisfiedFilled: typeof import('~icons/carbon/face-dissatisfied-filled')['default']
    CarbonFaceSatisfied: typeof import('~icons/carbon/face-satisfied')['default']
    CarbonFaceSatisfiedFilled: typeof import('~icons/carbon/face-satisfied-filled')['default']
    CarbonInteractions: typeof import('~icons/carbon/interactions')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonThfaceSatisfiedFilled: typeof import('~icons/carbon/thface-satisfied-filled')['default']
    CarbonThumbsDown: typeof import('~icons/carbon/thumbs-down')['default']
    CarbonThumbsDownFilled: typeof import('~icons/carbon/thumbs-down-filled')['default']
    CarbonThumbsUp: typeof import('~icons/carbon/thumbs-up')['default']
    CarbonThumbsUpFilled: typeof import('~icons/carbon/thumbs-up-filled')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    SignIn: typeof import('./components/SignIn.vue')['default']
  }
}

export { }
